import { MenuItem, Order, Reservation } from './store';

export const menuItems: MenuItem[] = [
  // Coffee
  {
    id: 'coffee-1',
    name: 'Brew Haven Espresso',
    category: 'Coffee',
    price: 180,
    description: 'Rich, bold espresso made from premium arabica beans',
    image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    isNew: true,
    rating: 4.8,
    reviews: 245,
  },
  {
    id: 'coffee-2',
    name: 'Cappuccino Delight',
    category: 'Coffee',
    price: 220,
    description: 'Smooth cappuccino with velvety milk foam and cinnamon sprinkle',
    image: 'https://images.pexels.com/photos/34097/taylor-swift.jpg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 'coffee-3',
    name: 'Latte Art Master',
    category: 'Coffee',
    price: 240,
    description: 'Premium latte with artistic milk foam designs',
    image: 'https://images.pexels.com/photos/3407880/pexels-photo-3407880.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.9,
    reviews: 312,
  },
  {
    id: 'coffee-4',
    name: 'Americano Classic',
    category: 'Coffee',
    price: 160,
    description: 'Double espresso diluted with hot water for smooth taste',
    image: 'https://images.pexels.com/photos/886521/pexels-photo-886521.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.6,
    reviews: 156,
  },

  // Cold Coffee
  {
    id: 'cold-1',
    name: 'Iced Mocha',
    category: 'Cold Coffee',
    price: 280,
    description: 'Chilled espresso with chocolate and ice cream',
    image: 'https://images.pexels.com/photos/3407880/pexels-photo-3407880.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    isNew: true,
    rating: 4.8,
    reviews: 203,
  },
  {
    id: 'cold-2',
    name: 'Cold Brew Bliss',
    category: 'Cold Coffee',
    price: 260,
    description: 'Smooth cold brew coffee with cream',
    image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.7,
    reviews: 178,
  },

  // Tea
  {
    id: 'tea-1',
    name: 'Green Tea Serenity',
    category: 'Tea',
    price: 150,
    description: 'Fresh green tea with jasmine flowers',
    image: 'https://images.pexels.com/photos/326900/pexels-photo-326900.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: 'tea-2',
    name: 'Masala Chai Traditional',
    category: 'Tea',
    price: 120,
    description: 'Authentic Indian spiced tea made with real spices',
    image: 'https://images.pexels.com/photos/326900/pexels-photo-326900.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.6,
    reviews: 267,
  },

  // Momos
  {
    id: 'momos-1',
    name: 'Steamed Veg Momos',
    category: 'Momos',
    price: 240,
    description: 'Handcrafted vegetable momos with signature dipping sauce',
    image: 'https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.9,
    reviews: 445,
  },
  {
    id: 'momos-2',
    name: 'Paneer Momos',
    category: 'Momos',
    price: 280,
    description: 'Premium paneer momos with herbs and spices',
    image: 'https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    isNew: true,
    rating: 4.8,
    reviews: 356,
  },
  {
    id: 'momos-3',
    name: 'Chicken Momos',
    category: 'Momos',
    price: 300,
    description: 'Tender chicken momos with aromatic filling',
    image: 'https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: false,
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 'momos-4',
    name: 'Fried Momos',
    category: 'Momos',
    price: 260,
    description: 'Crispy fried vegetable momos with chutney',
    image: 'https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.6,
    reviews: 203,
  },

  // Snacks
  {
    id: 'snacks-1',
    name: 'Crispy French Fries',
    category: 'Snacks',
    price: 160,
    description: 'Golden crispy fries with herb seasoning',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.5,
    reviews: 312,
  },
  {
    id: 'snacks-2',
    name: 'Garlic Bread Deluxe',
    category: 'Snacks',
    price: 200,
    description: 'Toasted bread with garlic butter and fresh herbs',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.7,
    reviews: 245,
  },
  {
    id: 'snacks-3',
    name: 'Club Sandwich',
    category: 'Snacks',
    price: 280,
    description: 'Triple-layered sandwich with chicken, bacon, and vegetables',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: false,
    rating: 4.8,
    reviews: 198,
  },

  // Desserts
  {
    id: 'desserts-1',
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    price: 320,
    description: 'Warm chocolate cake with molten center and vanilla ice cream',
    image: 'https://images.pexels.com/photos/1120573/pexels-photo-1120573.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    isNew: true,
    rating: 4.9,
    reviews: 389,
  },
  {
    id: 'desserts-2',
    name: 'Cheesecake Heaven',
    category: 'Desserts',
    price: 280,
    description: 'Creamy cheesecake with berry compote',
    image: 'https://images.pexels.com/photos/1120573/pexels-photo-1120573.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.7,
    reviews: 267,
  },
  {
    id: 'desserts-3',
    name: 'Brownie Bliss',
    category: 'Desserts',
    price: 240,
    description: 'Fudgy brownie with nuts and dark chocolate',
    image: 'https://images.pexels.com/photos/1120573/pexels-photo-1120573.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    isVeg: true,
    rating: 4.8,
    reviews: 321,
  },
];

export const specialOffers = [
  {
    id: 'offer-1',
    title: "Today's Special",
    description: 'Momos + Coffee combo at 30% off',
    discount: 30,
    validUntil: new Date(Date.now() + 24 * 60 * 60 * 1000),
  },
  {
    id: 'offer-2',
    title: 'Weekend Combo',
    description: 'Buy any 2 items, get dessert free',
    discount: 0,
    validUntil: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'offer-3',
    title: 'Student Discount',
    description: '20% off on all items with valid student ID',
    discount: 20,
    validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Priya Sharma',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    review: 'The momos are absolutely divine! Best coffee experience ever. The ambiance is so cozy and Instagram-worthy.',
    rating: 5,
    verified: true,
  },
  {
    id: 2,
    name: 'Rahul Verma',
    image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    review: 'Premium quality with reasonable prices. The staff is welcoming and the green ambiance is refreshing.',
    rating: 5,
    verified: true,
  },
  {
    id: 3,
    name: 'Anjali Patel',
    image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    review: 'Love the eco-friendly approach. Every detail is thoughtfully designed. Definitely coming back!',
    rating: 4.8,
    verified: true,
  },
  {
    id: 4,
    name: 'Vikram Singh',
    image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    review: 'Great workspace for remote work. WiFi is fast, coffee is excellent, and the vibe is perfect.',
    rating: 4.7,
    verified: true,
  },
];

export const galleryImages = [
  {
    id: 1,
    image: 'https://images.pexels.com/photos/1121100/pexels-photo-1121100.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    category: 'Indoor',
    title: 'Main Seating Area',
  },
  {
    id: 2,
    image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    category: 'Coffee',
    title: 'Premium Coffee Preparation',
  },
  {
    id: 3,
    image: 'https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    category: 'Food',
    title: 'Handcrafted Momos',
  },
  {
    id: 4,
    image: 'https://images.pexels.com/photos/1120573/pexels-photo-1120573.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    category: 'Desserts',
    title: 'Chocolate Lava Cake',
  },
  {
    id: 5,
    image: 'https://images.pexels.com/photos/1121100/pexels-photo-1121100.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    category: 'Indoor',
    title: 'Moss Wall Feature',
  },
  {
    id: 6,
    image: 'https://images.pexels.com/photos/3407880/pexels-photo-3407880.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
    category: 'Coffee',
    title: 'Latte Art',
  },
];

export const events = [
  {
    id: 1,
    title: 'Live Jazz Nights',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    time: '19:00',
    description: 'Enjoy smooth jazz while sipping premium coffee',
    attendees: 234,
    image: 'https://images.pexels.com/photos/3646172/pexels-photo-3646172.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
  },
  {
    id: 2,
    title: 'Coffee Tasting Workshop',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    time: '10:00',
    description: 'Learn to distinguish between different coffee origins',
    attendees: 45,
    image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
  },
  {
    id: 3,
    title: 'Open Mic Poetry Night',
    date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
    time: '20:00',
    description: 'Share your poetry and connect with fellow poets',
    attendees: 178,
    image: 'https://images.pexels.com/photos/2248488/pexels-photo-2248488.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
  },
];

export const timeSlots = [
  '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
  '12:00', '12:30', '13:00', '13:30', '14:00', '14:30',
  '15:00', '15:30', '16:00', '16:30', '17:00', '17:30',
  '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00',
];

export const businessHours = [
  { day: 'Monday', open: '09:00 AM', close: '11:00 PM' },
  { day: 'Tuesday', open: '09:00 AM', close: '11:00 PM' },
  { day: 'Wednesday', open: '09:00 AM', close: '11:00 PM' },
  { day: 'Thursday', open: '09:00 AM', close: '11:00 PM' },
  { day: 'Friday', open: '09:00 AM', close: '12:00 AM' },
  { day: 'Saturday', open: '08:00 AM', close: '12:00 AM' },
  { day: 'Sunday', open: '08:00 AM', close: '11:00 PM' },
];

export const faqData = [
  {
    id: 1,
    question: 'Do you offer online ordering?',
    answer: 'Yes! You can browse our menu and place orders online. We offer both delivery and pickup options.',
  },
  {
    id: 2,
    question: 'What are your momos made of?',
    answer: 'Our momos are handcrafted fresh daily using premium ingredients and traditional recipes.',
  },
  {
    id: 3,
    question: 'Do you have WiFi?',
    answer: 'Yes, we offer high-speed WiFi free for all customers.',
  },
  {
    id: 4,
    question: 'Can I make reservations for large groups?',
    answer: 'Absolutely! We welcome group reservations. Please contact us for bookings of 15+ people.',
  },
  {
    id: 5,
    question: 'Are your ingredients organic?',
    answer: 'We prioritize fresh, locally-sourced ingredients whenever possible.',
  },
  {
    id: 6,
    question: 'Do you offer vegetarian options?',
    answer: 'Yes, we have extensive vegetarian and vegan options across all categories.',
  },
];
